### ISSUE TITLE
FPGA code of project

### ISSUE THREAD

**Issue by insekt** [Eideticom/eid-hermes#38]
Hi All,
I found your project and it looks very interesting. You made a great work.
I would like to try it but it seems FPGA part of project is not covered by this repo.

I see this note:
> This part of the project implements an eid-hermes bitstream which can run on an AWS F1 instance. This code will be contained in this repo and will consist mostly of RTL.

Are you still going to publish this part? If so, when do you plan to do it?

**Comment by iomartin** [comment]
Hi @insekt, thanks for the interest in our project.

The FPGA part of the project is currently sitting on an open PR (https://github.com/Eideticom/eid-hermes/pull/35), you can take a look there. It supports all eBPF functions (except call) and works on AWS F1 instances.
